# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgisdashboard
                                 A QGIS plugin
 QGIS Dashboard that enables users to create their own customized dashboards
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Isaac Enage
        email                : isaacenagework@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
# QAction lives in QtWidgets on Qt5 (PyQt5) but moved to QtGui on Qt6 (PyQt6);
# import defensively so the plugin works across QGIS 3.22 – 4.99.
try:                                          # Qt6 / PyQt6
    from qgis.PyQt.QtGui import QAction
except ImportError:                           # pragma: no cover - Qt5 / PyQt5
    from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py. The compiled resources file
# is optional: if it has not been generated (pyrcc5) we fall back to loading
# the icon from the plugin directory, so the plugin still installs and runs.
try:
    from .resources import *  # noqa: F401,F403
    _HAS_RESOURCES = True
except ImportError:
    _HAS_RESOURCES = False

from .icons import logo_icon
from .window import DashboardWindow


class qgisdashboard:
    """QGIS Plugin Implementation.

    Hosts the dashboard as a standalone top-level window
    (``DashboardWindow``) — not a dock. A single checkable toolbar/menu action
    shows/hides the window. The dashboard (tiles, layout, connections, theme)
    is persisted into the ``.qgz`` project file on save and restored on open.
    """

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')
        locale = locale[0:2] if locale else 'en'
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'qgisdashboard_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QGIS Dashboard')
        self.action = None
        self.window = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('qgisdashboard', message)

    def _icon(self):
        """Return the plugin icon for the toolbar / Plugins menu.

        Prefers the branded gradient logo (rendered from an embedded SVG, the
        same art used for the dashboard window's title-bar icon). Falls back
        to the compiled Qt resource and then the on-disk ``icon.png`` so the
        plugin still shows an icon if ``QtSvg`` is somehow unavailable.
        """
        logo = logo_icon()
        if not logo.isNull():
            return logo
        if _HAS_RESOURCES:
            icon = QIcon(':/plugins/qgis_dashboard/icon.png')
            if not icon.isNull():
                return icon
        return QIcon(os.path.join(self.plugin_dir, 'icon.png'))

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        self.action = QAction(self._icon(), self.tr(u'QGIS Dashboard'),
                              self.iface.mainWindow())
        self.action.setCheckable(True)
        self.action.triggered.connect(self.toggle)
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToMenu(self.menu, self.action)
        self.actions.append(self.action)

        # Persist on project save; restore on open; clear on new project.
        QgsProject.instance().writeProject.connect(self._on_write)
        self.iface.projectRead.connect(self._on_read)
        self.iface.newProjectCreated.connect(self._on_new)

    # ---- window lifecycle ----

    def _ensure_window(self):
        if self.window is None:
            self.window = DashboardWindow(self.iface, self.iface.mainWindow())
            # untick the toolbar action when the user closes the window
            self.window.closed.connect(lambda: self.action.setChecked(False))
            # The window is created lazily on first toggle, AFTER projectRead has
            # already fired — so it never saw load_from_project() and would open
            # to a blank default canvas. Sync it to the current project now: an
            # existing dashboard opens to its canvas, anything else (fresh/empty
            # project) greets the user with the Home/Start screen.
            self.window.load_from_project()
        return self.window

    def toggle(self, checked):
        win = self._ensure_window()
        if checked:
            # restore_from_bubble shows the window (clearing any minimized puck),
            # raises and activates it.
            win.restore_from_bubble()
        else:
            win.hide_all()

    # ---- project save/load hooks ----

    def _on_write(self, _doc):
        if self.window:
            self.window.save_to_project()

    def _on_read(self):
        self._ensure_window().load_from_project()

    def _on_new(self):
        if self.window:
            self.window.clear_all()
            self.window.show_start()

    # ---- headless scripting API (QGIS MCP / PyQGIS automation) ----
    #
    # These thin wrappers let an automation client build dashboards without the
    # GUI: ``plugins['qgis_dashboards'].build_dashboard(spec)`` etc. The heavy
    # lifting lives in ``scripting.py`` (a stable, documented facade). Each
    # ensures the window exists first, so a single call works from a cold
    # start.

    def build_dashboard(self, spec, show=True, save=True):
        """Build a whole dashboard from a *spec* dict (see :func:`api_reference`).

        Replaces any current dashboard. Returns ``{pages, elements, warnings}``.
        """
        from .scripting import build_dashboard
        win = self._ensure_window()
        result = build_dashboard(win, spec, show=show, save=save)
        if show and self.action is not None:
            self.action.setChecked(True)
        return result

    def add_element(self, type_name, config=None, at=None, layer=None,
                    connect_to=None):
        """Add a single element to the current page; returns its element id."""
        from .scripting import add_element
        win = self._ensure_window()
        return add_element(win, type_name, config, at=at, layer=layer,
                           connect_to=connect_to)

    def list_layers(self):
        """List the project's layers + fields (to pick what tiles bind to)."""
        from .scripting import list_layers
        return list_layers()

    def api_reference(self):
        """Return the scripting API reference text (spec schema, types, themes)."""
        from .scripting import api_reference
        return api_reference()

    def dashboard_window(self, show=False):
        """Return the live :class:`DashboardWindow` (created on first call)."""
        win = self._ensure_window()
        if show:
            win.restore_from_bubble()
            if self.action is not None:
                self.action.setChecked(True)
        return win

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI.

        Crucially also tears down every connection this plugin made to
        long-lived singletons (the ``QgsProject`` instance and ``iface``). Those
        outlive the plugin, so a connection left behind after unload/reload
        fires into deleted Python/C++ objects on the next project save, layer
        add/remove, etc. — surfacing as ``RuntimeError: wrapped C/C++ object ...
        has been deleted``.
        """
        try:
            QgsProject.instance().writeProject.disconnect(self._on_write)
        except (TypeError, RuntimeError):
            pass
        try:
            self.iface.projectRead.disconnect(self._on_read)
        except (TypeError, RuntimeError):
            pass
        try:
            self.iface.newProjectCreated.disconnect(self._on_new)
        except (TypeError, RuntimeError):
            pass
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        self.actions = []
        if self.window:
            self.window.cleanup()   # drop the window's QgsProject connections
            self.window.close()
            self.window.deleteLater()
            self.window = None
